server:
  error:
    include-message: always
    include-binding-errors: always
  max-http-header-size: 1048576
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/burpi_db?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowPublicKeyRetrieval=true
    username: root
    hikari:
      maximum-pool-size: 300
      minimum-idle: 3
      idleTimeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true

twilio:
  account_sid: AC2b9d19ee98c4d3b6cce1841085a16b65
  auth_token: 2fb80010363ad121adae9cf166b7add5
  trial_number: +17659994208